package com.example.unisyncpoe.ui.auth

import android.util.Log
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.unisyncpoe.data.model.User
import com.example.unisyncpoe.data.model.UserRole
import com.example.unisyncpoe.data.remote.AuthResponse
import com.example.unisyncpoe.data.repository.AuthRepository
import com.example.unisyncpoe.data.remote.AuthInterceptor
import com.example.unisyncpoe.util.AuthManager
import com.example.unisyncpoe.util.CredentialStorage
import com.google.firebase.auth.FirebaseAuth
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import javax.inject.Inject

/**
 * ViewModel for authentication operations
 */
@HiltViewModel
class AuthViewModel @Inject constructor(
    private val authRepository: AuthRepository,
    private val authManager: AuthManager,
    private val authInterceptor: AuthInterceptor,
    private val credentialStorage: CredentialStorage,
    private val firebaseAuth: FirebaseAuth
) : ViewModel() {
    
    companion object {
        private const val TAG = "AuthViewModel"
    }
    
    private val _uiState = MutableStateFlow<AuthUiState>(AuthUiState.Idle)
    val uiState: StateFlow<AuthUiState> = _uiState.asStateFlow()
    
    private val _isLoggedIn = MutableStateFlow(authManager.isLoggedIn())
    val isLoggedIn: StateFlow<Boolean> = _isLoggedIn.asStateFlow()
    
    init {
        checkAuthState()
    }
    
    private fun checkAuthState() {
        viewModelScope.launch {
            if (authManager.isLoggedIn() && authManager.getUserId() != null) {
                _isLoggedIn.value = true
            }
        }
    }
    
    fun register(
        email: String,
        password: String,
        name: String,
        role: UserRole,
        studentId: String? = null,
        lecturerId: String? = null,
        coordinatorId: String? = null
    ) {
        viewModelScope.launch {
            _uiState.value = AuthUiState.Loading
            
            val user = User(
                id = "", // Will be generated by backend
                email = email,
                name = name,
                role = role,
                studentId = studentId,
                lecturerId = lecturerId,
                coordinatorId = coordinatorId
            )
            
            authRepository.register(user, password).fold(
                onSuccess = { registeredUser ->
                    // Save user info for demo/offline mode
                    if (!registeredUser.isSynced) {
                        // Demo/offline mode - save locally
                        authManager.saveUserId(registeredUser.id)
                        authManager.saveUserEmail(registeredUser.email)
                        authManager.saveUserRole(registeredUser.role.name)
                        authManager.setLoggedIn(true)
                        Log.d(TAG, "Registration successful (offline mode): ${registeredUser.email}")
                    } else {
                        // Normal mode - user registered on server
                        authManager.saveUserId(registeredUser.id)
                        authManager.saveUserEmail(registeredUser.email)
                        authManager.saveUserRole(registeredUser.role.name)
                        authManager.setLoggedIn(true)
                        Log.d(TAG, "Registration successful: ${registeredUser.email}")
                    }
                    _uiState.value = AuthUiState.Success(registeredUser)
                },
                onFailure = { exception ->
                    val errorMsg = exception.message ?: "Registration failed"
                    _uiState.value = AuthUiState.Error(errorMsg)
                    Log.e(TAG, "Registration failed: $errorMsg", exception)
                }
            )
        }
    }
    
    fun login(email: String, password: String) {
        viewModelScope.launch {
            _uiState.value = AuthUiState.Loading
            
            authRepository.login(email, password).fold(
                onSuccess = { authResponse ->
                    // Save auth data
                    authManager.saveAuthToken(authResponse.token)
                    authManager.saveUserId(authResponse.user.id)
                    authManager.saveUserEmail(authResponse.user.email)
                    authManager.saveUserRole(authResponse.user.role.name)
                    authManager.setLoggedIn(true)
                    
                    // Save credentials securely for biometric login (only if biometric is enabled)
                    if (authManager.isBiometricEnabled()) {
                        credentialStorage.saveCredentials(email, password)
                        Log.d(TAG, "Credentials saved for biometric login")
                    }
                    
                    // Set token in interceptor
                    authInterceptor.setAuthToken(authResponse.token)
                    
                    // Sign in with Firebase Auth for Firestore access
                    signInWithFirebaseAuth(authResponse.user.id, email)
                    
                    _isLoggedIn.value = true
                    _uiState.value = AuthUiState.Success(authResponse.user)
                    Log.d(TAG, "Login successful")
                },
                onFailure = { exception ->
                    _uiState.value = AuthUiState.Error(exception.message ?: "Login failed")
                    Log.e(TAG, "Login failed", exception)
                }
            )
        }
    }
    
    fun logout() {
        viewModelScope.launch {
            authRepository.logout()
            authManager.clearAuthData()
            credentialStorage.clearCredentials() // Clear saved credentials on logout
            authInterceptor.setAuthToken(null)
            _isLoggedIn.value = false
            _uiState.value = AuthUiState.Idle
            Log.d(TAG, "User logged out")
        }
    }
    
    fun clearError() {
        _uiState.value = AuthUiState.Idle
    }
    
    /**
     * Sign in with Firebase Auth using anonymous authentication
     * This is required for Firestore security rules to work
     */
    private fun signInWithFirebaseAuth(userId: String, email: String) {
        viewModelScope.launch {
            try {
                // Sign out any existing user first
                firebaseAuth.signOut()
                
                // Sign in anonymously - Firestore rules will check the user document
                // We use anonymous auth because we're using custom authentication
                val result = firebaseAuth.signInAnonymously().await()
                Log.d(TAG, "Firebase Auth sign-in successful for user: ${result.user?.uid}")
                
                // Note: Firestore rules check request.auth.uid, but since we're using anonymous auth,
                // we need to ensure the user document exists with the same ID or update rules
                // For now, this allows Firestore operations to work
            } catch (e: Exception) {
                Log.e(TAG, "Firebase Auth sign-in failed: ${e.message}", e)
                // Don't fail login if Firebase Auth fails - Firestore might still work
                // or we can update security rules to be more permissive
            }
        }
    }
}

sealed class AuthUiState {
    object Idle : AuthUiState()
    object Loading : AuthUiState()
    data class Success(val user: User) : AuthUiState()
    data class Error(val message: String) : AuthUiState()
}

